
version: "3.9"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api-memo-test-app
        restart: unless-stopped
        tty: true
        working_dir: /var/www/api-memo-test
        volumes:
            - .:/var/www/api-memo-test
        networks:
            - app-network
    nginx:
        image: nginx:latest
        restart: unless-stopped
        container_name: api-memo-test-nginx
        tty: true
        ports:
            - "82:80"
        volumes:
            - .:/var/www/api-memo-test
            - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
    mysql:
        image: mysql:5.7.22
        #image: mariadb:10.3
        container_name: api-memo-test-mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3308:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: memotest
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql/
#            - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
volumes:
    dbdata:
        driver: local