import './globals.css';

import React from 'react';

import type { Metadata } from 'next';

import { Atkinson_Hyperlegible } from '@next/font/google';

import { GameProvider } from '../components/game-provider';

const hyperlegible = Atkinson_Hyperlegible({
  subsets: ['latin'],
  weight: ['400','700']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GameProvider>
    <html lang="en">
      <body className={hyperlegible.className}>{children}</body>
    </html>
    </GameProvider>
  );
}
